force-app/main/default/objects/Grain_Price__c/Grain_Price__c.object-meta.xml
<CustomObject>
    <description>Object to house the price of grain, by quality, by site, that Manildra is currently purchasing</description>
    <label>Grain Price</label>
    <nameField>
        <label>Grain Price Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grain Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grain_Price__c/fields/Bin_Grade__c.field-meta.xml
<CustomField>
    <fullName>Bin_Grade__c</fullName>
    <description>Picklist field to hold potential Bin Grade options</description>
    <label>Bin Grade</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grain_Price__c/fields/Price_Per_Metric_Tonne__c.field-meta.xml
<CustomField>
    <fullName>Price_Per_Metric_Tonne__c</fullName>
    <description>Currency field to hold the Price Per Metric Tonne that Manildra is currently purchasing this grade of grain for</description>
    <label>Price Per Metric Tonne</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Grain_Price__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <description>Master-Detail with Site for Cash Price to effectively work as a Junction Object between Site and Product to show which products are currently being purchased, by which Site, by which Bin Grade, at what cost.</description>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipName>Cash_Prices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <description>Custom object to house Site information, opening hours managed within SF.</description>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/GROW_SiteGrainPriceViewCtrlTest.cls
/*
* 
* 
*/

@isTest
private class GROW_SiteGrainPriceViewCtrlTest {

    @testSetup
    static void setup() {

        // Insert Site
        Site__c testSite = TestDataFactory.getSite('New Test Site');
        insert testSite;
        
        Grain_Price__c grainPrice = new Grain_Price__c();
        grainPrice.Site__c = testSite.Id;
        grainPrice.Bin_Grade__c = 'binGrade';
        grainPrice.Price_Per_Metric_Tonne__c = 10;
        insert grainPrice;

        grainPrice = new Grain_Price__c();
        grainPrice.Site__c = testSite.Id;
        grainPrice.Bin_Grade__c = 'binGrade1';
        grainPrice.Price_Per_Metric_Tonne__c = 0;
        insert grainPrice;
        
    }
     
    
    @isTest
    static void testPositive(){
        GROW_SiteGrainPriceViewCtrl.getGrainPrices();
    }    


}