force-app/main/default/objects/Order_Grid__c/Order_Grid__c.object-meta.xml
<CustomObject>
    <description>Used to manage frequently ordered products</description>
    <label>Order Grid</label>
    <nameField>
        <label>Order Grid Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Grids</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Grid__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Account which made these Orders</description>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Grids</relationshipLabel>
    <relationshipName>Order_Grids</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Grid__c/fields/Avg_Of_Orders__c.field-meta.xml
<CustomField>
    <fullName>Avg_Of_Orders__c</fullName>
    <description>Average of last 6 orders</description>
    <formula>( Order1__c +  Order2__c +  Order3__c +  Order4__c +  Order5__c +  Order6__c ) / 6</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Average of last 6 orders</inlineHelpText>
    <label>Avg Of Orders</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Grid__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <description>Product Code</description>
    <label>Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Grid__c/fields/Default_Order__c.field-meta.xml
<CustomField>
    <fullName>Default_Order__c</fullName>
    <description>Default Quantity of order</description>
    <label>Default Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Grid__c/fields/Order1__c.field-meta.xml
<CustomField>
    <fullName>Order1__c</fullName>
    <inlineHelpText>First of the last 6 Orders Invoiced</inlineHelpText>
    <label>Order1</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Grid__c/fields/Order1_Date__c.field-meta.xml
<CustomField>
    <fullName>Order1_Date__c</fullName>
    <label>Order1_Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order_Grid__c/fields/Order2__c.field-meta.xml
<CustomField>
    <fullName>Order2__c</fullName>
    <description>Second of the last 6 Odrers Invoiced</description>
    <label>Order2</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Grid__c/fields/Order2_Date__c.field-meta.xml
<CustomField>
    <fullName>Order2_Date__c</fullName>
    <description>This is the date for Order 2. This field is to be displayed on the Grid header.</description>
    <label>Order2 Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Order_Grid__c/fields/Order3__c.field-meta.xml
<CustomField>
    <fullName>Order3__c</fullName>
    <description>Third of the last 6 Orders Invoiced</description>
    <label>Order3</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Grid__c/fields/Order3_Date__c.field-meta.xml
<CustomField>
    <fullName>Order3_Date__c</fullName>
    <label>Order3_Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order_Grid__c/fields/Order4__c.field-meta.xml
<CustomField>
    <fullName>Order4__c</fullName>
    <description>Fourth of the last 6 orders Invoiced.</description>
    <label>Order4</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Grid__c/fields/Order4_Date__c.field-meta.xml
<CustomField>
    <fullName>Order4_Date__c</fullName>
    <label>Order4_Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Order_Grid__c/fields/Order5__c.field-meta.xml
<CustomField>
    <fullName>Order5__c</fullName>
    <description>Fifth of the last 6 Orders Invoiced.</description>
    <label>Order5</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Grid__c/fields/Order5_Date__c.field-meta.xml
<CustomField>
    <fullName>Order5_Date__c</fullName>
    <label>Order5_Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order_Grid__c/fields/Order6__c.field-meta.xml
<CustomField>
    <fullName>Order6__c</fullName>
    <description>Sixth of the last 6 Orders Invoiced.</description>
    <label>Order6</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Grid__c/fields/Order6_Date__c.field-meta.xml
<CustomField>
    <fullName>Order6_Date__c</fullName>
    <label>Order6_Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Order_Grid__c/fields/Order_Required__c.field-meta.xml
<CustomField>
    <fullName>Order_Required__c</fullName>
    <label>Order Required</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Grid__c/fields/OrderPending__c.field-meta.xml
<CustomField>
    <fullName>OrderPending__c</fullName>
    <description>Pending Order quantity.</description>
    <label>OrderPending</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Grid__c/fields/Pack_Size__c.field-meta.xml
<CustomField>
    <fullName>Pack_Size__c</fullName>
    <label>Pack Size</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Grid__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <description>Product Price</description>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order_Grid__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Order Grids</relationshipLabel>
    <relationshipName>Order_Grids</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Grid__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <description>Total Price is unit price multiplied with quantity.</description>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order_Grid__c/fields/Total_Price_Formula__c.field-meta.xml
<CustomField>
    <fullName>Total_Price_Formula__c</fullName>
    <formula>Price__c  *  Order_Required__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order_Grid__c/fields/Total_Weight__c.field-meta.xml
<CustomField>
    <fullName>Total_Weight__c</fullName>
    <description>This is product unit weight multiplied by quantity being ordered.</description>
    <label>Total Weight</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Grid__c/fields/Total_Weight_Formula__c.field-meta.xml
<CustomField>
    <fullName>Total_Weight_Formula__c</fullName>
    <formula>TEXT( Pack_Size__c *  Order_Required__c )+&apos;kg&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Weight</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OrderGridControler.cls
public without sharing class OrderGridControler {

    @AuraEnabled(cacheable=true)
    public static List<Order_Grid__c> getOrderList(String accountId) {

        system.debug('The Account id is:'+accountId);
        return [SELECT Id, Code__c, Order1_Date__c, Order2_Date__c,Order3_Date__c,Order4_Date__c,Order5_Date__c,Order6_Date__c,Price__c, Total_Price_Formula__c,Total_Weight_Formula__c, Pack_Size__c, Default_Order__c, 
                        Product_Name__c, Order_Required__c, Order1__c, Order2__c, Order3__c, Order4__c, Order5__c, Order6__c, Avg_Of_Orders__c, Total_Price__c, 
                        Total_Weight__c, OrderPending__c FROM Order_Grid__c where Account_Name__c =: accountId AND Code__c!=''];
    }

    @AuraEnabled
    public static void setRequiredOrder(String  selectedColumn, String accountId ) {

        String column = '';
        column = selectedColumn;
        Double orderQuantity = 0.0;

        List<Order_Grid__c> orderGridList =  [SELECT Id, Code__c,Price__c, Pack_Size__c, Default_Order__c,OrderPending__c, Order1__c, 
                                                Order2__c, Order3__c, Order4__c, Order5__c, Order6__c , Avg_Of_Orders__c, Product_Name__c, Order_Required__c, 
                                                Total_Price__c, Total_Weight__c FROM Order_Grid__c where Account_Name__c =: accountId];

        List<Order_Grid__c> updateOrderGridList = new List<Order_Grid__c>();
        for(Order_Grid__c orderGridObj : orderGridList){
            if(column.equals('Order1__c')){
                if(orderGridObj.Order1__c == null){
                    orderQuantity = 0.0;
                }else {
                    orderQuantity = orderGridObj.Order1__c;
                }
                orderGridObj.Order_Required__c = orderGridObj.Order1__c;
                if(orderGridObj.Price__c!= null ){
                orderGridObj.Total_Price__c = orderGridObj.Price__c * orderQuantity;
                orderGridObj.Total_Weight__c = orderGridObj.Pack_Size__c * orderQuantity;
                }
            }
            if(column.equals('Order2__c')){
                if(orderGridObj.Order2__c == null){
                    orderQuantity = 0.0;
                }else {
                    orderQuantity = orderGridObj.Order2__c;
                }
                orderGridObj.Order_Required__c = orderGridObj.Order2__c;
                if(orderGridObj.Price__c!= null ){
                orderGridObj.Total_Price__c = orderGridObj.Price__c * orderQuantity;
                orderGridObj.Total_Weight__c = orderGridObj.Pack_Size__c *orderQuantity;
                }
            }
            if(column.equals('Order3__c')){
                if(orderGridObj.Order3__c == null){
                    orderQuantity = 0.0;
                }else {
                    orderQuantity = orderGridObj.Order3__c;
                }
                orderGridObj.Order_Required__c = orderGridObj.Order3__c;
                if(orderGridObj.Price__c!= null){
                orderGridObj.Total_Price__c = orderGridObj.Price__c * orderQuantity;
                orderGridObj.Total_Weight__c = orderGridObj.Pack_Size__c * orderQuantity;
                }
            }
            if(column.equals('Order4__c')){
                if(orderGridObj.Order4__c == null){
                    orderQuantity = 0.0;
                }else {
                    orderQuantity = orderGridObj.Order4__c;
                }
                orderGridObj.Order_Required__c = orderGridObj.Order4__c;
                if(orderGridObj.Price__c!= null ){
                orderGridObj.Total_Price__c = orderGridObj.Price__c * orderQuantity;
                orderGridObj.Total_Weight__c = orderGridObj.Pack_Size__c * orderQuantity;
                }
            }
            if(column.equals('Order5__c')){
                if(orderGridObj.Order5__c == null){
                    orderQuantity = 0.0;
                }else {
                    orderQuantity = orderGridObj.Order5__c;
                }
                orderGridObj.Order_Required__c = orderGridObj.Order5__c;
                if(orderGridObj.Price__c!= null ){
                    orderGridObj.Total_Price__c = orderGridObj.Price__c * orderQuantity;
                    orderGridObj.Total_Weight__c = orderGridObj.Pack_Size__c * orderQuantity;
                }
            }
            if(column.equals('Order6__c')){
                if(orderGridObj.Order6__c == null){
                    orderQuantity = 0.0;
                }else {
                    orderQuantity = orderGridObj.Order6__c;
                }
                orderGridObj.Order_Required__c = orderGridObj.Order6__c;
                if(orderGridObj.Price__c!= null ){
                orderGridObj.Total_Price__c = orderGridObj.Price__c * orderQuantity;
                orderGridObj.Total_Weight__c = orderGridObj.Pack_Size__c * orderQuantity;
                }
            }
            if(column.equals('OrderPending__c')){
                if(orderGridObj.OrderPending__c == null){
                    orderQuantity = 0.0;
                }else {
                    orderQuantity = orderGridObj.OrderPending__c;
                }
                orderGridObj.Order_Required__c = orderGridObj.OrderPending__c;
                if(orderGridObj.Price__c!= null ){
                orderGridObj.Total_Price__c = orderGridObj.Price__c * orderQuantity;
                orderGridObj.Total_Weight__c = orderGridObj.Pack_Size__c * orderQuantity;
                }
            }
            if(column.equals('Avg_Of_Orders__c')){
                if(orderGridObj.Avg_Of_Orders__c == null){
                    orderQuantity = 0.0;
                }else {
                    orderQuantity = orderGridObj.Avg_Of_Orders__c;
                }
                orderGridObj.Order_Required__c = orderGridObj.Avg_Of_Orders__c;
                if(orderGridObj.Price__c!= null ){
                orderGridObj.Total_Price__c = orderGridObj.Price__c * orderQuantity;
                orderGridObj.Total_Weight__c = orderGridObj.Pack_Size__c * orderQuantity;
                }
            }
            
            updateOrderGridList.add(orderGridObj);
        }
        update updateOrderGridList;

    }

    @AuraEnabled
    public static string updateOrderGrid(Object data) {
        List<Order_Grid__c> ordersForUpdate = (List<Order_Grid__c>) JSON.deserialize(
            JSON.serialize(data),
            List<Order_Grid__c>.class
        );
        System.debug('The value of orders to update'+ordersForUpdate);
        System.debug('The value of orders to update'+ordersForUpdate.size());
        if(ordersForUpdate.size()> 0){
            
            System.debug('The value of ordersForUpdate[0].id'+ordersForUpdate[0].id);
        }
        try {
            update ordersForUpdate;
            return 'Success: contacts updated successfully';
        }
        catch (Exception e) {
            return 'The following exception has occurred: ' + e.getMessage();
        }
    }

    //Create Required Order from the required quantity field in the Order Grid custom object. 
    @AuraEnabled
    public static string createOrder(String customerUserId, String accountId, String deliveryDate, String paymentMethod) {
        system.debug('createOrder delivery Date:'+deliveryDate);
        system.debug('Account id passed in accountId: '+accountId);
        try {
            //Check is the Cat already exists.
            WebCart cart ;//= new WebCart();
            CartDeliveryGroup deliveryGroup = new CartDeliveryGroup();
            List<WebCart> cartList = [select id , name , CreatedDate,status, ownerid  from webcart where ownerid = :customerUserId and status = 'Active' and accountid=:accountId Limit 1];
            List<CartItem> cartItemToDel = new List<CartItem>();
            WebStore	store = [select id from WebStore where name = 'Manildra B2B' Limit 1];  
            if (cartList.size() > 0){
                cart = cartList[0];
                cartItemToDel = [Select id from CartItem where cartid =: cart.id ];
                delete cartItemToDel;
            }
            //If cart does not exist then create a new Cart. 
            if(cart == null){          
                cart = new WebCart();  
                cart.name = 'CartX';                
                cart.AccountId = Id.valueOf(accountid);//get from userid->Contact->Account
                cart.OwnerId = customerUserId;//get from community userid lwc
                cart.WebStoreId =store.id;//id.valueOf('0ZEO0000000CaRMOA0');//cadecode for now. 
              
                insert cart;
                //insert the Cart Delivery Group. 
                deliveryGroup.name = 'WYDG';
                deliveryGroup.cartid = cart.id;
                deliveryGroup.DeliverToName = 'WY';
                system.debug('Setting the delivery Date: '+Date.valueOf(deliveryDate));
                deliveryGroup.DesiredDeliveryDate = Date.valueOf(deliveryDate);
                insert deliveryGroup;
            }else{
                ID cartId = cart.id;
                cart.IsRepricingNeeded = true;
                update cart;
                deliveryGroup = [select id,DesiredDeliveryDate   from CartDeliveryGroup where cartid =: cartId  Limit 1];
                system.debug('Setting the delivery Date in else loop: '+Date.valueOf(deliveryDate));
                deliveryGroup.DesiredDeliveryDate = Date.valueOf(deliveryDate);
                update deliveryGroup;
                
            }
            /**
             *Get data from Order Grid to Populate the cart.
             *-quantity is required Order.
             *-Prive is Price__c 
             */

            List<CartItem> newCartItemsList = new List<CartItem>();
            List<Order_Grid__c> orderData = [Select id, Order_Required__c, Price__c ,product__c, product__r.StockKeepingUnit
                                            from Order_Grid__c 
                                            where Account_Name__c =:accountid];
            for(Order_Grid__c orderGridObj : orderData){

                CartItem newCartItem = new CartItem();
                newCartItem.name = 'CartItemx';
                newCartItem.type = 'Product';
                newCartItem.sku = orderGridObj.product__r.StockKeepingUnit;
                newCartItem.CartDeliveryGroupid = deliveryGroup.id;
                newCartItem.CartId = cart.id;
                newCartItem.Product2Id = orderGridObj.product__c;                
    
                if(orderGridObj.Order_Required__c != null && orderGridObj.Order_Required__c > 0){        
                    newCartItem.Quantity = orderGridObj.Order_Required__c;
                    newCartItem.TotalPrice = orderGridObj.Price__c * orderGridObj.Order_Required__c; 
                    newCartItem.TotalPriceAfterAllAdjustments = orderGridObj.Price__c * orderGridObj.Order_Required__c;
                    newCartItem.TotalPromoAdjustmentAmount = 0;
                   // newCartItem.TotalPromoAdjustmentTaxAmount = 0;
                    newCartItem.TotalAdjustmentAmount = 0;
                }
                else {
                    newCartItem.Quantity = 0;
                    newCartItem.TotalPrice = orderGridObj.Price__c * 0; 
                }
                newCartItem.TotalLineAmount = orderGridObj.Price__c; //get from Order Grid
                //get from Order Grid
                newCartItem.ListPrice = orderGridObj.Price__c;
                newCartItem.UnitAdjustedPrice = orderGridObj.Price__c;

                if(newCartItem.quantity > 0 && newCartItem.ListPrice >0){
                    newCartItemsList.add(newCartItem);
                }
            }

            insert newCartItemsList;
            //Add discount item for Online Payment.
            System.debug('Discount Mathod value:'+paymentMethod);
            if(paymentMethod.equals('payOnline') ){
                DiscountController.addDiscountItem(cart.id, deliveryGroup.id);

            }
            return cart.Id;
        }
        catch (Exception e) {
            
            System.debug('.getStackTraceString():  '+e.getStackTraceString());
            System.debug('.getMessage():  '+e.getMessage());
            System.debug('.getCause():  '+e.getCause());
            System.debug('.getLineNumber():  '+ e.getLineNumber());
            return 'The following exception has occurred: ' + e.getMessage();
        }
    }
    @AuraEnabled
    public static string saveOrderLineItem(String objId, String value){

        try{
        ID orderGridid = ID.valueOf(objId);
        Order_Grid__c orderGridObj = [Select id , order1__c, Order_Required__c from Order_Grid__c where id =:orderGridid Limit 1];
        orderGridObj.Order_Required__c = Integer.valueOf(value);
        update orderGridObj;
        return 'Success: contacts updated successfully';
        }catch (Exception e) {
            return 'The following exception has occurred: ' + e.getMessage();
        }
    }

    @AuraEnabled
    public static string setDeliveryDate(String customerUserId, String accountId, String deliveryDate){
        try {
                  //Check is the Cat already exists.
                  WebCart cart ;//= new WebCart();
                  CartDeliveryGroup deliveryGroup = new CartDeliveryGroup();
                  List<WebCart> cartList = [select id , name , CreatedDate,status, ownerid  from webcart where ownerid = :customerUserId and status = 'Active' and accountid=:accountId Limit 1];
                  WebStore	store = [select id from WebStore where name = 'Manildra B2B' Limit 1];  
                  if (cartList.size() > 0)
                  cart = cartList[0];
                  //If cart does not exist then create a new Cart. 
                  if(cart == null){          
                      cart = new WebCart();  
                      cart.name = 'CartX';                
                      cart.AccountId = Id.valueOf(accountid);//get from userid->Contact->Account
                      cart.OwnerId = customerUserId;//get from community userid lwc
                      cart.WebStoreId = store.id;//id.valueOf('0ZEO0000000CaRMOA0');//cadecode for now.               
                      insert cart;
                      //insert the Cart Delivery Group. 
                      deliveryGroup.name = 'WYDG';
                      deliveryGroup.cartid = cart.id;
                      deliveryGroup.DeliverToName = 'WY';
                      system.debug('Setting the delivery Date: '+Date.valueOf(deliveryDate));
                      deliveryGroup.DesiredDeliveryDate = Date.valueOf(deliveryDate);
                      insert deliveryGroup;
                  }else{
                      ID cartId = cart.id;
                      cart.IsRepricingNeeded = true;
                      update cart;
                      deliveryGroup = [select id,DesiredDeliveryDate   from CartDeliveryGroup where cartid =: cartId  Limit 1];
                      system.debug('Setting the delivery Date in else loop: '+Date.valueOf(deliveryDate));
                      deliveryGroup.DesiredDeliveryDate = Date.valueOf(deliveryDate);
                      update deliveryGroup;
                      
                  }
                  return 'Success: DesiredDeliveryDate updated successfully';
            
        } catch (Exception e) {
            //throw new AuraHandledException(e.getMessage());
            return 'The following exception has occurred: ' + e.getMessage();
        }
    }
    /**
    * @Description : Batch process populated the Price for each Item. 
    *  step1 get all the items in grid and the Priductid
    *  step2 Get the Price books based on Delivery Date
    *  step3 get the Price book entry based on ProdcutId
    *  step4 get the Price from Price Book entry and Populate the Grid Item. 
    */

    @AuraEnabled
    public static string setPriceInGrid(String accountId, String deliveryDate){
        try {
            //Adding time value to make it compatable with DateTime field. 
            String dDateTimeStr = deliveryDate + ' 00:00:00';
            system.debug('The value accountId: '+accountId);
            system.debug('The value dDateTimeStr: '+dDateTimeStr);

            Datetime deliveryDateTime = Datetime.valueOfGMT(dDateTimeStr);
            List<Order_Grid__c> updateOrderGridList = new List<Order_Grid__c>();
            Map<Id, Order_Grid__c> productIDtoOrderGridObjMap = new Map<Id, Order_Grid__c>();
            List<Order_Grid__c> orderGridList = [select id, Product__c, Price__c from Order_Grid__c where Account_Name__c =:accountId];
            List<ID> productIds = new List<ID>();
            for(Order_Grid__c orderGridObj :orderGridList ){
                productIds.add(orderGridObj.Product__c);
            }

            //carete Productid to Order grid Map.
            for(Order_Grid__c orderObj:orderGridList ){
                productIDtoOrderGridObjMap.put(orderObj.Product__c, orderObj);
            }
            List<BuyerGroupMember>  buyerGroupMemList = [select id, buyerGroupId from BuyerGroupMember where buyerId =: accountId];
            system.debug('The value buyerGroupMemList: '+buyerGroupMemList);
            ID buyerGroupId = buyerGroupMemList[0].buyerGroupId;
            List<BuyerGroupPricebook>  buyerGroupPricebookList = [select id, Pricebook2Id, buyerGroupId from BuyerGroupPricebook where buyerGroupId =: buyerGroupId];
            List<ID> priceBookIds = new List<ID>();
            List<ID> validPriceBookIds = new List<ID>();
            for(BuyerGroupPricebook buyerGroupPricebookObj :buyerGroupPricebookList ){
                priceBookIds.add(buyerGroupPricebookObj.Pricebook2Id);
            }
            system.debug('The value priceBookIds: '+priceBookIds);
            system.debug('The value deliveryDateTime: '+deliveryDateTime);
            List<Pricebook2> priceBookList = [Select id from Pricebook2 where id in: (priceBookIds) and ValidFrom	<=: deliveryDateTime and  ValidTo >=: deliveryDateTime ];
            system.debug('The value priceBookList size: '+priceBookList.size());
            Map<id,Order_Grid__c> checkDuplicate = new Map<Id, Order_Grid__c>();
            if(priceBookList.size() > 0 ){
                for(Pricebook2 pbookObj: priceBookList){
                    validPriceBookIds.add(pbookObj.id);
                }
                system.debug('The value validPriceBookIds: '+validPriceBookIds);
                // ID priceBookId = priceBookList[0].id;
                List<PricebookEntry> priceBookEntryList = [select id, product2Id, UnitPrice, IsActive 
                                                                from PriceBookEntry 
                                                                where Pricebook2Id in: validPriceBookIds 
                                                                        and Product2Id in: productIds];

                system.debug('The value priceBookEntryList: '+priceBookEntryList);

                for(PricebookEntry pBookentry: priceBookEntryList){
                    if(checkDuplicate.get(pBookentry.Product2Id) == null){
                        Order_Grid__c orderGrid =  productIDtoOrderGridObjMap.get(pBookentry.product2Id); 
                        if(!pBookentry.IsActive){
                            orderGrid.price__c = 0;    
                        }else{
                            orderGrid.price__c =  pBookentry.UnitPrice;
                            
                        }
                        checkDuplicate.put(pBookentry.product2Id,orderGrid);
                        updateOrderGridList.add(orderGrid);
                    }

                }

            }
            //Set 0 for all Products which do not have a Price Book Entry.
            for(Order_Grid__c oGridObj: orderGridList){
                if(checkDuplicate.size() == 0 || checkDuplicate.get(oGridObj.Product__c) == null){
                    oGridObj.Price__c = 0;
                    updateOrderGridList.add(oGridObj);
                }
            }
            system.debug('The value id updateOrderGridList: '+updateOrderGridList);
            update updateOrderGridList;
                
            return 'Success: updateOrderGridList: ' +updateOrderGridList;
            
        } catch (Exception e) {
            //throw new AuraHandledException(e.getMessage());
            return 'The following exception has occurred: ' + e.getMessage();
        }
    }  

}