force-app/main/default/objects/Order_Grid__c/Order_Grid__c.object-meta.xml
<CustomObject>
    <description>Used to manage frequently ordered products</description>
    <label>Order Grid</label>
    <nameField>
        <label>Order Grid Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Grids</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Grid__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Account which made these Orders</description>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Grids</relationshipLabel>
    <relationshipName>Order_Grids</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Grid__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <description>Product Code</description>
    <label>Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Grid__c/fields/Order1__c.field-meta.xml
<CustomField>
    <fullName>Order1__c</fullName>
    <inlineHelpText>First of the last 6 Orders Invoiced</inlineHelpText>
    <label>Order1</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Grid__c/fields/Order1_Date__c.field-meta.xml
<CustomField>
    <fullName>Order1_Date__c</fullName>
    <label>Order1_Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order_Grid__c/fields/Order2__c.field-meta.xml
<CustomField>
    <fullName>Order2__c</fullName>
    <description>Second of the last 6 Odrers Invoiced</description>
    <label>Order2</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Grid__c/fields/Order2_Date__c.field-meta.xml
<CustomField>
    <fullName>Order2_Date__c</fullName>
    <description>This is the date for Order 2. This field is to be displayed on the Grid header.</description>
    <label>Order2 Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Order_Grid__c/fields/Order3__c.field-meta.xml
<CustomField>
    <fullName>Order3__c</fullName>
    <description>Third of the last 6 Orders Invoiced</description>
    <label>Order3</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Grid__c/fields/Order3_Date__c.field-meta.xml
<CustomField>
    <fullName>Order3_Date__c</fullName>
    <label>Order3_Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order_Grid__c/fields/Order4__c.field-meta.xml
<CustomField>
    <fullName>Order4__c</fullName>
    <description>Fourth of the last 6 orders Invoiced.</description>
    <label>Order4</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Grid__c/fields/Order4_Date__c.field-meta.xml
<CustomField>
    <fullName>Order4_Date__c</fullName>
    <label>Order4_Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Order_Grid__c/fields/Order5__c.field-meta.xml
<CustomField>
    <fullName>Order5__c</fullName>
    <description>Fifth of the last 6 Orders Invoiced.</description>
    <label>Order5</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Grid__c/fields/Order5_Date__c.field-meta.xml
<CustomField>
    <fullName>Order5_Date__c</fullName>
    <label>Order5_Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order_Grid__c/fields/Order6__c.field-meta.xml
<CustomField>
    <fullName>Order6__c</fullName>
    <description>Sixth of the last 6 Orders Invoiced.</description>
    <label>Order6</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Grid__c/fields/Order6_Date__c.field-meta.xml
<CustomField>
    <fullName>Order6_Date__c</fullName>
    <label>Order6_Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Order_Grid__c/fields/Pack_Size__c.field-meta.xml
<CustomField>
    <fullName>Pack_Size__c</fullName>
    <label>Pack Size</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Grid__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <description>Product Price</description>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order_Grid__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Order Grids</relationshipLabel>
    <relationshipName>Order_Grids</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Weight_kg__c.field-meta.xml
<CustomField>
    <fullName>Weight_kg__c</fullName>
    <description>Stores the product weight in kg&apos;s</description>
    <inlineHelpText>Product Weight</inlineHelpText>
    <label>Weight (kg)</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/OrderGridBatchProcess.cls
global class OrderGridBatchProcess implements Database.Batchable<sObject>{
	public Database.QueryLocator start(Database.BatchableContext context){
		String query = 'SELECT Id, Name,' + 
                        '(Select Id, Accountid, OrderedDate '+
                        'FROM Orders '+
                        'WHERE Order.status = "Completed" '+
                        'ORDER BY OrderedDate Asc LIMIT 6)'+
						'FROM Account';
		return Database.getQueryLocator(query);
	}

	public void execute(Database.BatchableContext context, List<Account> accountList){
		processOrdersForAccounts(accountList);
	}

	public void finish(Database.BatchableContext context){
		//
	}

	public void processOrdersForAccounts(List<Account> accountWithOrdersList){
		try{
             
            Set<Id> orderIdSet = new Set<Id>();
            for (Account acc : accountWithOrdersList){
                for (Order o : acc.Orders){
                    orderIdSet.add(o.Id);
                }
            }
            
            List<OrderItem> orderItemList = [
                SELECT Id, Order.Id,ListPrice, Weight_kg__c, Product_Name__c, Product_Code__c, Quantity, TotalPrice, Order.OrderedDate, Product2Id, Order.Accountid
                FROM OrderItem
                WHERE Order.id IN :orderIdSet and Order.status = 'Completed'
                ORDER BY Order.OrderedDate Asc
            ];
            
            Map<String, Integer> orderDateAndSortOrderMap = new Map<String, Integer>();
            
            for(Account acc : accountWithOrdersList){
                if(acc.Orders.size() >0) {
                    for(Integer i=0; i<acc.Orders.size(); i++) {
                        orderDateAndSortOrderMap.put(String.valueOf(acc.Id+'#'+acc.Orders[i].Id+'#'+acc.Orders[i].OrderedDate), i);
                    }
                }
            }
            
            List<Order_Grid__c> orderGridList = new List<Order_Grid__c>();
            Order_Grid__c orderGridItem = new Order_Grid__c();
            
            for (OrderItem orderItemObj : orderItemList){
                
                orderGridItem = new Order_Grid__c();
                String sortOrder = orderDateAndSortOrderMap.get(orderItemObj.Order.AccountId+'#'+orderItemObj.OrderId+'#'+orderItemObj.Order.OrderedDate);
                orderGridItem.Product_Name__c = orderItemObj.Product_Name__c;
                orderGridItem.Price__c = orderItemObj.ListPrice;
                orderGridItem.Code__c = orderItemObj.Product_Code__c;
                orderGridItem.Account_Name__c = orderItemObj.Order.Accountid;
                orderGridItem.Pack_Size__c = orderItemObj.Weight_kg__c == null ? 0 : orderItemObj.Weight_kg__c;
                orderGridItem.Product__c =orderItemObj.Product2Id;

                
                switch on orderDateAndSortOrderMap.get(sortOrder) {
                    when 0 {
                        orderGridItem.Order1__c = orderItemObj.Quantity;
                        orderGridItem.Order1_Date__c = orderItemObj.Order.OrderedDate.date();
                    }
                    
                    when 1 {
                        orderGridItem.Order2__c = orderItemObj.Quantity;
                        orderGridItem.Order2_Date__c = orderItemObj.Order.OrderedDate.date();
                    }
                    
                    when 2 {
                        orderGridItem.Order3__c = orderItemObj.Quantity;
                        orderGridItem.Order3_Date__c = orderItemObj.Order.OrderedDate.date();
                    }
                    
                    when 3 {
                        orderGridItem.Order4__c = orderItemObj.Quantity;
                        orderGridItem.Order4_Date__c = orderItemObj.Order.OrderedDate.date();
                    }
                    
                    when 4 {
                        orderGridItem.Order5__c = orderItemObj.Quantity;
                        orderGridItem.Order5_Date__c = orderItemObj.Order.OrderedDate.date();
                    }
                    
                    when 5 {
                        orderGridItem.Order6__c = orderItemObj.Quantity;
                        orderGridItem.Order6_Date__c = orderItemObj.Order.OrderedDate.date();
                    }
                }
                orderGridList.add(orderGridItem);
            }
            upsert orderGridList;
        }
        catch(Exception e) {
            
        }
	}
}