force-app/main/default/objects/Account/fields/Buyer_Group__c.field-meta.xml
<CustomField>
    <fullName>Buyer_Group__c</fullName>
    <label>Buyer Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Buyer_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/B2B_Customer_Delivery_Date__c/B2B_Customer_Delivery_Date__c.object-meta.xml
<CustomObject>
    <description>This object will have the upcoming delivery dates for a B2B Customer. Data in this object will be inserted by a batch process.</description>
    <label>Preferred Delivery Day</label>
    <nameField>
        <displayFormat>CDD-{0000}</displayFormat>
        <label>Delivery Day Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Preferred Delivery Days</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/B2B_Customer_Delivery_Date__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>B2B_Customer_Delivery_Dates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/B2B_Customer_Delivery_Date__c/fields/Day__c.field-meta.xml
<CustomField>
    <fullName>Day__c</fullName>
    <label>Preferred Delivery Day</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Delivery_Dates</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grain_Price__c/Grain_Price__c.object-meta.xml
<CustomObject>
    <description>Object to house the price of grain, by quality, by site, that Manildra is currently purchasing</description>
    <label>Grain Price</label>
    <nameField>
        <label>Grain Price Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grain Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Grain_Price__c/fields/Bin_Grade__c.field-meta.xml
<CustomField>
    <fullName>Bin_Grade__c</fullName>
    <description>Picklist field to hold potential Bin Grade options</description>
    <label>Bin Grade</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grain_Price__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <description>Master-Detail with Site for Cash Price to effectively work as a Junction Object between Site and Product to show which products are currently being purchased, by which Site, by which Bin Grade, at what cost.</description>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipName>Cash_Prices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Buyer_Group__c.field-meta.xml
<CustomField>
    <fullName>Buyer_Group__c</fullName>
    <inlineHelpText>Buyer Group if Appliciable</inlineHelpText>
    <label>Buyer Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Buyer_Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Operation_Hours__c/Operation_Hours__c.object-meta.xml
<CustomObject>
    <description>Custom Object to house the Operation Hours of Sites, to dynamically expose them to the Grower&apos;s Portal</description>
    <label>Operation Hours</label>
    <nameField>
        <label>Operation Hours Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Operation Hours</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Operation_Hours__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <description>Master-Detail to indicate which Site the Operation hours is referring to, managed from within SF.</description>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Operation Hours</relationshipLabel>
    <relationshipName>Operation_Hours</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Grid__c/Order_Grid__c.object-meta.xml
<CustomObject>
    <description>Used to manage frequently ordered products</description>
    <label>Order Grid</label>
    <nameField>
        <label>Order Grid Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Grids</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Grid__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Account which made these Orders</description>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Grids</relationshipLabel>
    <relationshipName>Order_Grids</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Grid__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Order Grids</relationshipLabel>
    <relationshipName>Order_Grids</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/PricebookExternalID__c.field-meta.xml
<CustomField>
    <fullName>PricebookExternalID__c</fullName>
    <externalId>true</externalId>
    <label>PricebookExternalID</label>
    <length>35</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/PricebookEntryExternalID__c.field-meta.xml
<CustomField>
    <fullName>PricebookEntryExternalID__c</fullName>
    <description>Unique Pricebook Entry ID matching to as400 - CustomerNumber+ItemCode+ContractStartDate</description>
    <externalId>true</externalId>
    <label>PriceEntryExternalID</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <description>Custom object to house Site information, opening hours managed within SF.</description>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Site__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>Address field to be exposed onto the Grower&apos;s Portal, managed from within Salesforce</description>
    <label>Address</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/BHC__c.field-meta.xml
<CustomField>
    <fullName>BHC__c</fullName>
    <description>Picklist field to indicate which organisation owns the Site, coming in from AGBOSS.</description>
    <label>BHC</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manildra</fullName>
            </value>
            <value>
                <fullName>Graincorp</fullName>
            </value>
            <value>
                <fullName>AWB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Business_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bakery</fullName>
    </customValue>
    <customValue>
        <fullName>Distributor</fullName>
    </customValue>
    <customValue>
        <fullName>Ethanol</fullName>
    </customValue>
    <customValue>
        <fullName>Industrial</fullName>
    </customValue>
    <customValue>
        <fullName>Manufacturing</fullName>
    </customValue>
    <customValue>
        <fullName>Petfoods</fullName>
    </customValue>
    <customValue>
        <fullName>Retail</fullName>
    </customValue>
    <customValue>
        <fullName>Wholesaler</fullName>
    </customValue>
    <customValue>
        <fullName>Meat</fullName>
    </customValue>
    <customValue>
        <fullName>Export</fullName>
    </customValue>
    <masterLabel>Business Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Buyer_Groups.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Export</fullName>
    </customValue>
    <customValue>
        <fullName>Domestic</fullName>
    </customValue>
    <customValue>
        <fullName>Bakers Delight</fullName>
    </customValue>
    <customValue>
        <fullName>Aldi Stores</fullName>
    </customValue>
    <customValue>
        <fullName>Arnotts</fullName>
    </customValue>
    <customValue>
        <fullName>Bidvest</fullName>
    </customValue>
    <customValue>
        <fullName>Boral</fullName>
    </customValue>
    <customValue>
        <fullName>BP Group of Customers</fullName>
    </customValue>
    <customValue>
        <fullName>Carter Holt Harvey</fullName>
    </customValue>
    <customValue>
        <fullName>Costco Group</fullName>
    </customValue>
    <customValue>
        <fullName>CSR</fullName>
    </customValue>
    <customValue>
        <fullName>Caltex Group</fullName>
    </customValue>
    <customValue>
        <fullName>Fosters</fullName>
    </customValue>
    <customValue>
        <fullName>Country Wide</fullName>
    </customValue>
    <customValue>
        <fullName>Donation Accounts</fullName>
    </customValue>
    <customValue>
        <fullName>Freedom Fuels</fullName>
    </customValue>
    <customValue>
        <fullName>Goodman Fielder</fullName>
    </customValue>
    <customValue>
        <fullName>Greens Group</fullName>
    </customValue>
    <customValue>
        <fullName>Coles Group</fullName>
    </customValue>
    <customValue>
        <fullName>General Mills</fullName>
    </customValue>
    <customValue>
        <fullName>george western foods</fullName>
    </customValue>
    <customValue>
        <fullName>Holland American Line</fullName>
    </customValue>
    <customValue>
        <fullName>Just Fuel</fullName>
    </customValue>
    <customValue>
        <fullName>Kimberly Clark Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Kelloggs</fullName>
    </customValue>
    <customValue>
        <fullName>Kerry Ingredients</fullName>
    </customValue>
    <customValue>
        <fullName>Kraft Foods (Cadbury previously)</fullName>
    </customValue>
    <customValue>
        <fullName>Krispy Kreme</fullName>
    </customValue>
    <customValue>
        <fullName>Knauf Plasterboard</fullName>
    </customValue>
    <customValue>
        <fullName>Liberty</fullName>
    </customValue>
    <masterLabel>Buyer Groups</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Delivery_Dates.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Monday</fullName>
    </customValue>
    <customValue>
        <fullName>Tuesday</fullName>
    </customValue>
    <customValue>
        <fullName>Wednesday</fullName>
    </customValue>
    <customValue>
        <fullName>Thursday</fullName>
    </customValue>
    <customValue>
        <fullName>Friday</fullName>
    </customValue>
    <masterLabel>Delivery Dates</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {
    public static List<Account> createAccountsWithOpps(Integer numAccts, Integer numOppsPerAcct) {
        List<Account> accts = new List<Account>();
        
        for(Integer i=0;i<numAccts;i++) {
            Account a = new Account(Name='TestAccount' + i);
            accts.add(a);
        }
        insert accts;
        
        List<Opportunity> opps = new List<Opportunity>();
        for (Integer j=0;j<numAccts;j++) {
            Account acct = accts[j];
            // For each account just inserted, add opportunities
            for (Integer k=0;k<numOppsPerAcct;k++) {
                opps.add(new Opportunity(Name=acct.Name + ' Opportunity ' + k,
                                       StageName='Prospecting',
                                       CloseDate=System.today().addMonths(1),
                                       AccountId=acct.Id));
            }
        }
        // Insert all opportunities for all accounts.
        insert opps;
        
        return accts;
    }
    public static List<Account> getAccounts(Integer numAccounts){
        List<Account> actList = new List<Account>();
        for(Integer i=0; i<numAccounts; i++){
            Account act = new Account();
            act.Name = 'TestAccount' + i;
            actList.add(act);
        }
        return actList;        
    } 
    public static Pricebook2 getCustomPricebook(String priceBookName){
        return new Pricebook2(Name = priceBookName, isActive = true, PricebookExternalID__c = string.valueOf(System.now()));
    }
    public static List<PricebookEntry> getPricebookEntry(Id priceBookId, List<product2> productList){
        List<PricebookEntry> entryList = new List<PricebookEntry>();
        integer i =0;
        for(product2 productVar : productList){            
            entryList.add(new PricebookEntry(Pricebook2Id = priceBookId, Product2Id = productVar.Id, UnitPrice = 100, PricebookEntryExternalID__c = String.valueOf(System.now().millisecond())+i));
            i++;
        }
        return entryList;
    }
    public static List<Order> getOrders(integer numOrders, Id accountId, Id priceBookId){
        List<Order> orderList = new List<Order>();
        for(integer i =0; i<numOrders; i++){
            orderList.add(new Order(accountId = accountId, Pricebook2Id = priceBookId, status = 'Draft', EffectiveDate = date.today()+i, OrderedDate = system.now()+i));
        }
        return orderList;
    } 
    public static OrderItem getOrderItem(Id orderId, Id productId,Id PricebookEntryId){
        return new OrderItem(orderId = orderId, Product2Id = productId, PricebookEntryId = PricebookEntryId, UnitPrice = 100, Quantity = 1);
    }
    public static B2B_Customer_Delivery_Date__c getPreferredDeliveryDay(Id accountId, String dayVar){
        B2B_Customer_Delivery_Date__c preferredDeliveryDay = new B2B_Customer_Delivery_Date__c();
        preferredDeliveryDay.Customer__c = accountId;
        preferredDeliveryDay.Day__c = dayVar;
        return preferredDeliveryDay;
    }
    public static List<product2> getProducts(Integer numProducts){
        List<product2> productList = new List<product2>();
        for(Integer i=0; i<numProducts ; i++){
            product2 productVar = new product2();
            productVar.Name = 'TestProduct' + i;
            productVar.IsActive = true;
            productList.add(productVar);
        }
        return productList;
    }
    public static List<Order_Grid__c> getOrderGrids(Map<Id,List<product2>> accountWithProductMap){
        List<Order_Grid__c> orderGrids = new List<Order_Grid__c>();
        for(Id actId: accountWithProductMap.keySet()){
            for(product2 productVar :accountWithProductMap.get(actId)){
                Order_Grid__c grid = new Order_Grid__c();
                grid.Account_Name__c = actId;
                grid.Product__c = productVar.Id; 
                orderGrids.add(grid);
            }
        }
        
        return orderGrids;
    }

    public static OrderDeliveryMethod getOrderDeliveryMethod(){
        OrderDeliveryMethod OrderDeliveryMethodVar = new OrderDeliveryMethod();
        OrderDeliveryMethodVar.Name = 'Standard Delivery Method';
        return OrderDeliveryMethodVar;
    }
    public static BuyerGroup getBuyerGroup(){
        return new BuyerGroup(name = 'TestBuyerGroup');
    }
    public static BuyerGroupMember getBuyerGroupMember(Id buyerGroupId, Id buyerId){
        return new BuyerGroupMember(BuyerId = buyerId, BuyerGroupId =buyerGroupId);
    }
    public static BuyerAccount getBuyerAccount(Id actRecordId){
        return new BuyerAccount(BuyerId = actRecordId, IsActive= true, Name= 'TestName');
    }
    public static webStore getWebStore(){
        return new webStore(name = 'TestName', DefaultLanguage='en_US');
    }
    public static WebStoreBuyerGroup getWebStoreBuyerGroup(Id webStoreId, Id BuyerGroupId){
        return new WebStoreBuyerGroup(WebStoreId = webStoreId, BuyerGroupId = BuyerGroupId);
    }

    public static WebCart getCart(Id webStoreId, Id accountId){
        return new WebCart(Name='Cart', WebStoreId=webStoreId, AccountId=accountId);
    }
    public static CartDeliveryGroup getCartDeliveryGroup(Id cartId){
        return new CartDeliveryGroup(Name='Default Delivery', CartId=cartId);
    }

    public static CartItem getCartItem(Id cartId, Id CartDeliveryGroupId, Id productId, String type, String skuStr, String itemName, decimal quantityStr, decimal totalPrice){
        CartItem cartItem = new CartItem(
            CartId=cartId, 
            Sku=skuStr, 
            Quantity=quantityStr, 
            Type=type, 
            Name=itemName, 
            TotalPrice=totalPrice,
            CartDeliveryGroupId=CartDeliveryGroupId,
            Product2Id = productId
        );
        return cartItem;
    }
    
    public static Site__c getSite(String name){
        Site__c testSite = new Site__c();
        testSite.Name = name;
        testSite.BHC__c = 'Manildra';
        testSite.Phone__c = '123456789';
        testSite.Address__c = 'Test Address';
        return testSite;
    }
    
    public static Operation_Hours__c getOperationHours(Id siteId){
        Operation_Hours__c testOpHours = new Operation_Hours__c();
        testOpHours.Site__c = siteId;
        return testOpHours;
    }
    
    public static Grain_Price__c getGrainPrice(Id siteId){
        Grain_Price__c grainPrice = new Grain_Price__c();
        grainPrice.Site__c = siteId;
        return grainPrice;
    }

    public static Grain_Price__c getGrainPrice(Id siteId, String binGrade){
        Grain_Price__c grainPrice = new Grain_Price__c();
        grainPrice.Site__c = siteId;
        grainPrice.Bin_Grade__c = binGrade;
        return grainPrice;
    } 
    
    public static Lead getLead(){
        Lead testLead = new Lead();
        testLead.LastName = 'test Lead';
        testLead.Business_Type__c = 'Bakery';
        testLead.Company = 'test Lead Company';
        testLead.Buyer_Group__c = 'Bakers Delight';
        return testLead;
    }
}