force-app/main/default/objects/Account/fields/Cut_Off_Time__c.field-meta.xml
<CustomField>
    <fullName>Cut_Off_Time__c</fullName>
    <description>Used for Default Order Creation batch process</description>
    <label>Cut Off Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Account/fields/Default_Order_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Default_Order_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Attribute used to create default order by batch process</description>
    <label>Default Order Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Lead_Time_In_Days__c.field-meta.xml
<CustomField>
    <fullName>Lead_Time_In_Days__c</fullName>
    <description>Used for default order creation batch.</description>
    <label>Lead Time(In Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tax_Exemption_Account__c.field-meta.xml
<CustomField>
    <fullName>Tax_Exemption_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tax Exemption Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CreateDefaultOrderBatch.cls
/**
 * @Description : 1.Generates the Default Order for the Customers considering below checks.
 *                 a. Default Order Enabled is true
 *                 b. Preferred Delivery Day 
 *                 c. Lead Time in Days
 *                 d. Cut off time
 *                 2. Creates default order and order line items and send confirmation to customer.  
 */
public class CreateDefaultOrderBatch implements Database.Batchable<sObject>, schedulable{

    public Database.QueryLocator start(Database.BatchableContext BC){
        String queryString = 'SELECT ID, Lead_Time_In_Days__C, Cut_Off_Time__C, Tax_Exemption_Account__c FROM Account WHERE Default_Order_Enabled__C= true';
        return Database.getQueryLocator(queryString); 
    }

    public void execute(Database.BatchableContext BC, List<SObject> scope){
        CreateDefaultOrderUtility.validateAndCreateDefaultOrders((List<Account>) scope);
    }
    public void execute(SchedulableContext SC) {
        database.executebatch(new CreateDefaultOrderBatch(), integer.valueOf(Label.CreateDefaultOrderBatchSize));
    } 
    public void finish(Database.BatchableContext BC){
        
    }
}