force-app/main/default/objects/Account/fields/Cut_Off_Time__c.field-meta.xml
<CustomField>
    <fullName>Cut_Off_Time__c</fullName>
    <description>Used for Default Order Creation batch process</description>
    <label>Cut Off Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Account/fields/Default_Order_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Default_Order_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Attribute used to create default order by batch process</description>
    <label>Default Order Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Lead_Time_In_Days__c.field-meta.xml
<CustomField>
    <fullName>Lead_Time_In_Days__c</fullName>
    <description>Used for default order creation batch.</description>
    <label>Lead Time(In Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/B2B_Customer_Delivery_Date__c/B2B_Customer_Delivery_Date__c.object-meta.xml
<CustomObject>
    <description>This object will have the upcoming delivery dates for a B2B Customer. Data in this object will be inserted by a batch process.</description>
    <label>Preferred Delivery Day</label>
    <nameField>
        <displayFormat>CDD-{0000}</displayFormat>
        <label>Delivery Day Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Preferred Delivery Days</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exception_Log__c/Exception_Log__c.object-meta.xml
<CustomObject>
    <label>Exception Log</label>
    <nameField>
        <displayFormat>E-{000000}</displayFormat>
        <label>Exception Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exception_Log__c/fields/Parent_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Parent_Record_Id__c</fullName>
    <label>Parent Record Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Grid__c/Order_Grid__c.object-meta.xml
<CustomObject>
    <description>Used to manage frequently ordered products</description>
    <label>Order Grid</label>
    <nameField>
        <label>Order Grid Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Grids</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Grid__c/fields/Order1__c.field-meta.xml
<CustomField>
    <fullName>Order1__c</fullName>
    <inlineHelpText>First of the last 6 Orders Invoiced</inlineHelpText>
    <label>Order1</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Grid__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <description>Product Price</description>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Tax_Required__c.field-meta.xml
<CustomField>
    <fullName>Tax_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tax Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CreateDefaultOrderBatchTest.cls
@isTest
private class CreateDefaultOrderBatchTest {
    @testSetup static void setup() {
        
        OrderDeliveryMethod orderDeliveryMethodVar = TestDataFactory.getOrderDeliveryMethod(); 
        insert orderDeliveryMethodVar;

        BuyerGroup buyerGroupVar = TestDataFactory.getBuyerGroup();
        insert buyerGroupVar;

        Account act = TestDataFactory.getAccounts(1)[0];
        act.Default_Order_Enabled__C = true;
        act.Lead_Time_In_Days__C = 0;
        act.Cut_Off_Time__C = Time.newinstance(11,0,0,0);
        insert act;

        BuyerAccount buyrAccount = TestDataFactory.getBuyerAccount(act.Id);
        insert buyrAccount;

        BuyerGroupMember BuyerGroupMemberVar = TestDataFactory.getBuyerGroupMember(buyerGroupVar.Id, act.Id);
        insert BuyerGroupMemberVar;

        WebStore webStoreVar = TestDataFactory.getWebStore();
        insert webStoreVar;

        WebStoreBuyerGroup webStoreBuyerGroupVar = TestDataFactory.getWebStoreBuyerGroup(webStoreVar.Id, buyerGroupVar.Id);
        insert webStoreBuyerGroupVar;

        Datetime dateToMatch = System.now();
        String dayOfWeek = dateToMatch.format('EEEE');
        B2B_Customer_Delivery_Date__c preferredDeliveryDay = TestDataFactory.getPreferredDeliveryDay(act.Id, dayOfWeek);
        insert preferredDeliveryDay;

        product2 deliveryChargeProductVar = TestDataFactory.getProducts(1)[0];
        deliveryChargeProductVar.Name = 'Shipping Charge for this delivery method';

        List<product2> prodList = TestDataFactory.getProducts(2);
        prodList[0].Tax_Required__C = true;
        prodList[1].Tax_Required__C = true;
        prodList.add(deliveryChargeProductVar);

        insert prodList;
        List<Order_Grid__c> orderGrids = TestDataFactory.getOrderGrids(new Map<Id,List<product2>>{act.Id => prodList});
        for(Order_Grid__c ordGrid : orderGrids){
            ordGrid.Order1__c = 6;
            ordGrid.Price__c = 100;
        }       
        insert orderGrids;
    }
    static testMethod void CreateDefaultOrderBatchTest() 
    {   Account act = [Select Id from Account Limit 1];
        Database.SaveResult sr = (Database.SaveResult)JSON.deserialize('{"success":false,"errors":[{"message":"You cannot do this...","statusCode":"FIELD_CUSTOM_VALIDATION_EXCEPTION"}]}', Database.SaveResult.class);
        Test.StartTest();
            CreateDefaultOrderBatch batchVar = new CreateDefaultOrderBatch();
            batchVar.execute(null);
            Exception_Log__c exceptionLog = CreateDefaultOrderUtility.contructExceptionLog(sr, act.Id, 'TestName');
        Test.StopTest();
        
        Order orderRecord = [Select Id from Order where accountId =: act.Id];
        system.assert(orderRecord != null);
        system.assert(exceptionLog.Parent_Record_Id__c== act.Id);
    }
}