force-app/main/default/objects/Account/fields/Delivery_Dates__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Dates__c</fullName>
    <label>Delivery Dates</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Delivery_Dates</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Delivery_Window_End__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Window_End__c</fullName>
    <inlineHelpText>The latest time a delivery can be made for the customer.</inlineHelpText>
    <label>Delivery Window End</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Account/fields/Delivery_Window_Start__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Window_Start__c</fullName>
    <inlineHelpText>The earliest time a delivery can be made for the customer.</inlineHelpText>
    <label>Delivery Window Start</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/B2B_Customer_Delivery_Date__c/B2B_Customer_Delivery_Date__c.object-meta.xml
<CustomObject>
    <description>This object will have the upcoming delivery dates for a B2B Customer. Data in this object will be inserted by a batch process.</description>
    <label>Preferred Delivery Day</label>
    <nameField>
        <displayFormat>CDD-{0000}</displayFormat>
        <label>Delivery Day Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Preferred Delivery Days</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/B2B_Customer_Delivery_Date__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>B2B_Customer_Delivery_Dates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/B2B_Customer_Delivery_Date__c/fields/Day__c.field-meta.xml
<CustomField>
    <fullName>Day__c</fullName>
    <label>Preferred Delivery Day</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Delivery_Dates</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/B2B_Customer_Delivery_Date__c/fields/Time_from__c.field-meta.xml
<CustomField>
    <fullName>Time_from__c</fullName>
    <label>Time from</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/B2B_Customer_Delivery_Date__c/fields/Time_To__c.field-meta.xml
<CustomField>
    <fullName>Time_To__c</fullName>
    <label>Time To</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Delivery_Dates__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Dates__c</fullName>
    <inlineHelpText>Customer&apos;s Available Delivery Dates</inlineHelpText>
    <label>Delivery Dates</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Delivery_Dates</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Delivery_Details__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Details__c</fullName>
    <inlineHelpText>Access and time, any other restrictions.</inlineHelpText>
    <label>Delivery Details</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Delivery_Window_End__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Window_End__c</fullName>
    <description>The latest time a delivery can be made for the customer.</description>
    <label>Delivery Window End</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Delivery_Window_Start__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Window_Start__c</fullName>
    <description>The earliest time a delivery can be made for the customer.</description>
    <label>Delivery Window Start</label>
    <type>Time</type>
</CustomField>

force-app/main/default/globalValueSets/Delivery_Dates.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Monday</fullName>
    </customValue>
    <customValue>
        <fullName>Tuesday</fullName>
    </customValue>
    <customValue>
        <fullName>Wednesday</fullName>
    </customValue>
    <customValue>
        <fullName>Thursday</fullName>
    </customValue>
    <customValue>
        <fullName>Friday</fullName>
    </customValue>
    <masterLabel>Delivery Dates</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LeadTriggerHandler.cls
//LeadTriggerHandler class
public with sharing class LeadTriggerHandler extends TriggerHandler {
    
    private Map<Id, Lead> newObjMap;
    private Map<Id, Lead> oldObjMap;
    private List<Lead> newObjList;
    private List<Lead> oldObjList;
    private Lead oldLead;
    
    public LeadTriggerHandler() {
        this.newObjMap = (Map<Id, Lead>) Trigger.newMap;
        this.newObjList = (List<Lead>) Trigger.new;
        this.oldObjMap = (Map<Id, Lead>) Trigger.oldMap;
        this.oldObjList = (List<Lead>) Trigger.old;
    }
    
    public override void beforeInsert() {
        //Trigger logic
    }
    
    public override void beforeUpdate() {
        //Trigger logic
    }
    
    public override void beforeDelete() {
        //Trigger logic
    }
    
    public override void afterInsert() {
        //Trigger logic
    }
    
    public override void afterUpdate() {
        
        List<Lead> lstConvertedLeads = new List<Lead>();
        
        for(Lead newLead: newObjList){
            oldLead = oldObjMap.get(newLead.Id);
            
            // [03-Sept-2021 - Mansoor] Create Preferred Delivery Day records when Lead is converted
            if(newLead.IsConverted && newLead.IsConverted != oldLead.IsConverted){
                
                // [03-Sept-2021 - Mansoor] Create a list of all converted leads and then pass it to separate method for processing
                lstConvertedLeads.add(newLead);
            }
        }
        
        if(lstConvertedLeads.size() > 0){
            createPreferredDeliveryDayRecords(lstConvertedLeads);
        }
    }
    
    public override void afterDelete() {
        //Trigger logic
    }
    
    public override void afterUndelete() {
        //Trigger logic
    }
    
    
    
    
    /**************	Helper Methods **************/
    
    private static void createPreferredDeliveryDayRecords(List<Lead> lstLeadsPrm){
        
        B2B_Customer_Delivery_Date__c prefDeliveryDay;
        List<Account> lstAccounts = new List<Account>();
        List<B2B_Customer_Delivery_Date__c> lstPrefDeliveryDaystoInsert = new List<B2B_Customer_Delivery_Date__c>();
        
        lstAccounts = [SELECT Id, Delivery_Dates__c, Delivery_Window_Start__c, Delivery_Window_End__c, Delivery_Details__c 
                       FROM Account
                       WHERE Id IN (SELECT ConvertedAccountId FROM Lead WHERE Id IN:lstLeadsPrm)
                       LIMIT 1000];
        
        for(Lead newLead: lstLeadsPrm){
            
            // Split the multi-picklist values into the separate selected values 
            List<String> selections = newLead.Delivery_Dates__c != null ? newLead.Delivery_Dates__c.split(';') : null;
            
            // Loop on the selected days and create corresponding Preferred Days Records\
            if (selections != null && !selections.isEmpty()) {
                for(String dayName : selections){
                    prefDeliveryDay = new B2B_Customer_Delivery_Date__c();
                    prefDeliveryDay.Day__c = dayName;
                    prefDeliveryDay.Time_from__c = newLead.Delivery_Window_Start__c;
                    prefDeliveryDay.Time_to__c = newLead.Delivery_Window_End__c;
                    prefDeliveryDay.Customer__c = newLead.ConvertedAccountId;
                    
                    lstPrefDeliveryDaystoInsert.add(prefDeliveryDay);
                }
            } 
        }
        
        if(lstPrefDeliveryDaystoInsert.size() > 0){
            database.insert(lstPrefDeliveryDaystoInsert);
        }
    }
}