force-app/main/default/objects/Operation_Hours__c/Operation_Hours__c.object-meta.xml
<CustomObject>
    <description>Custom Object to house the Operation Hours of Sites, to dynamically expose them to the Grower&apos;s Portal</description>
    <label>Operation Hours</label>
    <nameField>
        <label>Operation Hours Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Operation Hours</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Operation_Hours__c/fields/Closed__c.field-meta.xml
<CustomField>
    <fullName>Closed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox to indicate if a Site will be closed on this specific day, default unchecked, managed from within SF</description>
    <label>Closed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Operation_Hours__c/fields/Closing_Time__c.field-meta.xml
<CustomField>
    <fullName>Closing_Time__c</fullName>
    <description>Time field to indicate the closing time of the Site, managed from within SF.</description>
    <label>Closing Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Operation_Hours__c/fields/Open_Time__c.field-meta.xml
<CustomField>
    <fullName>Open_Time__c</fullName>
    <description>Time field to indicate the opening time of the Site, managed from within SF.</description>
    <label>Open Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Operation_Hours__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <description>Master-Detail to indicate which Site the Operation hours is referring to, managed from within SF.</description>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Operation Hours</relationshipLabel>
    <relationshipName>Operation_Hours</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <description>Custom object to house Site information, opening hours managed within SF.</description>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Site__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>Address field to be exposed onto the Grower&apos;s Portal, managed from within Salesforce</description>
    <label>Address</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/Site_Manager__c.field-meta.xml
<CustomField>
    <fullName>Site_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to User to represent the Site Manager</description>
    <label>Site Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/Site_Manager_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Site_Manager_Mobile__c</fullName>
    <description>Phone field to represent the Site Manager&apos;s Mobile</description>
    <label>Site Manager Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/Site_Related_Alert__c.field-meta.xml
<CustomField>
    <fullName>Site_Related_Alert__c</fullName>
    <description>Bin Grade/Site Manager will use this field to display any alert or message on the &quot;Operation Hours&quot; page on Grower&apos;s Portal</description>
    <label>Site Related Alert</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GROW_SiteOpHoursCtrl.cls
/*
* 
* 
*/

public with Sharing class GROW_SiteOpHoursCtrl {
    
    @AuraEnabled 
    public static List<SiteWrapper> getSites(){ 
        
        try{
            List<Site__c> lstParentSites = new List<Site__c>();
            List<SiteWrapper> lstSites = new List<SiteWrapper>();
            
            lstParentSites = [SELECT Id, Name, Phone__c, Address__c, Site_Related_Alert__c, Site_Manager__r.Name, Site_Manager_Mobile__c, 
                              (SELECT Id, Name, Open_Time__c, Closing_Time__c, Closed__c FROM Operation_Hours__r)
                              FROM Site__c 
                              ORDER BY Name ASC
                              LIMIT 50];
            
            if (lstParentSites.size() > 0){
                lstSites = transformSites(lstParentSites);
            }
            
            return lstSites;
        }
        catch (Exception e){
            throw new AuraHandledException (e.getMessage());
        }
    }
    
    public class SiteWrapper{
        
        @AuraEnabled public String Name{get;set;}
        @AuraEnabled public String Phone{get;set;}
        @AuraEnabled public String Address{get;set;}
        @AuraEnabled public String MonHours{get;set;}
        @AuraEnabled public String TueHours{get;set;}
        @AuraEnabled public String WedHours{get;set;}
        @AuraEnabled public String ThuHours{get;set;}
        @AuraEnabled public String FriHours{get;set;}
        @AuraEnabled public String SatHours{get;set;}
        @AuraEnabled public String SunHours{get;set;}
        @AuraEnabled public String SiteRelatedAlert{get;set;}
        @AuraEnabled public String SiteManagerName{get;set;}
        @AuraEnabled public String SiteManagerMobile{get;set;}
    }
    
    /* ------------- HELPER METHODS -------------- */
    
    private static List<SiteWrapper> transformSites(List<Site__c> lstSitesPrm){
        SiteWrapper newSite;
        List<SiteWrapper> lstSiteWrapper = new List<SiteWrapper>();
        
        for(Site__c st: lstSitesPrm){
            newSite = new SiteWrapper();
            newSite.Name = st.Name;
            newSite.Address = st.Address__c;
            newSite.Phone = st.Phone__c;
            newSite.SiteRelatedAlert = st.Site_Related_Alert__c;
            newSite.SiteManagerName = st.Site_Manager__r.Name;
            newSite.SiteManagerMobile = st.Site_Manager_Mobile__c;
            
            if (st.Operation_Hours__r.size() > 0){
                for (Operation_Hours__c opHours: st.Operation_Hours__r){
                    
                    if(opHours.Name == 'Monday'){
                        if (opHours.Closed__c) newSite.MonHours = 'Closed';
                        else  newSite.MonHours = getFormattedTime(opHours.Open_Time__c) + ' - ' + getFormattedTime(opHours.Closing_Time__c);
                    }
                    else if (opHours.Name == 'Tuesday'){
                        if (opHours.Closed__c) newSite.TueHours = 'Closed';
                        else  newSite.TueHours = getFormattedTime(opHours.Open_Time__c) + ' - ' + getFormattedTime(opHours.Closing_Time__c);
                    }
                    else if (opHours.Name == 'Wednesday'){
                        if (opHours.Closed__c) newSite.WedHours = 'Closed';
                        else  newSite.WedHours = getFormattedTime(opHours.Open_Time__c) + ' - ' + getFormattedTime(opHours.Closing_Time__c);
                    }
                    else if (opHours.Name == 'Thursday'){
                        if (opHours.Closed__c) newSite.ThuHours = 'Closed';
                        else  newSite.ThuHours = getFormattedTime(opHours.Open_Time__c) + ' - ' + getFormattedTime(opHours.Closing_Time__c);
                    }
                    else if (opHours.Name == 'Friday'){
                        if (opHours.Closed__c) newSite.FriHours = 'Closed';
                        else  newSite.FriHours = getFormattedTime(opHours.Open_Time__c) + ' - ' + getFormattedTime(opHours.Closing_Time__c);
                    }
                    else if (opHours.Name == 'Saturday'){
                        if (opHours.Closed__c) newSite.SatHours = 'Closed';
                        else  newSite.SatHours = getFormattedTime(opHours.Open_Time__c) + ' - ' + getFormattedTime(opHours.Closing_Time__c);
                    }
                    else if (opHours.Name == 'Sunday'){
                        if (opHours.Closed__c) newSite.SunHours = 'Closed';
                        else  newSite.SunHours = getFormattedTime(opHours.Open_Time__c) + ' - ' + getFormattedTime(opHours.Closing_Time__c);
                    }
                }
            }
            
            //system.debug('MMM -> Site Wrapper - newSite: '+newSite);
            lstSiteWrapper.add(newSite);
        }
        
        return lstSiteWrapper;
    }
    
    private static String getFormattedTime(Time t){
        if (t == null)
            return '';
        else{
            DateTime dt = DateTime.newInstance(Date.today(), t);
            return dt.format('hh:mm a');
        }
    } 
    
}