force-app/main/default/objects/Operation_Hours__c/Operation_Hours__c.object-meta.xml
<CustomObject>
    <description>Custom Object to house the Operation Hours of Sites, to dynamically expose them to the Grower&apos;s Portal</description>
    <label>Operation Hours</label>
    <nameField>
        <label>Operation Hours Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Operation Hours</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Operation_Hours__c/fields/Closing_Time__c.field-meta.xml
<CustomField>
    <fullName>Closing_Time__c</fullName>
    <description>Time field to indicate the closing time of the Site, managed from within SF.</description>
    <label>Closing Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Operation_Hours__c/fields/Open_Time__c.field-meta.xml
<CustomField>
    <fullName>Open_Time__c</fullName>
    <description>Time field to indicate the opening time of the Site, managed from within SF.</description>
    <label>Open Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Operation_Hours__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <description>Master-Detail to indicate which Site the Operation hours is referring to, managed from within SF.</description>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Operation Hours</relationshipLabel>
    <relationshipName>Operation_Hours</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <description>Custom object to house Site information, opening hours managed within SF.</description>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/GROW_SiteOpHoursCtrlTest.cls
/*
* 
* 
*/

@isTest
private class GROW_SiteOpHoursCtrlTest {
    
    
    @testSetup
    static void setup() {
        
        // Insert Site
        Site__c testSite = TestDataFactory.getSite('New Test Site');
        insert testSite;
        
        // Insert Operation hours
        List<Operation_Hours__c> lstOPHours = new List<Operation_Hours__c>();
        
        Operation_Hours__c opHours1 = TestDataFactory.getOperationHours(testSite.Id);
        opHours1.Name = 'Monday';
        opHours1.Open_Time__c = System.now().time();
        opHours1.Closing_Time__c = system.now().addHours(3).time();
        lstOPHours.add(opHours1);
        
        Operation_Hours__c opHours2 = TestDataFactory.getOperationHours(testSite.Id);
        opHours2.Name = 'Tuesday';
        opHours2.Open_Time__c = System.now().time();
        opHours2.Closing_Time__c = system.now().addHours(3).time();
        lstOPHours.add(opHours2);
        
        Operation_Hours__c opHours3 = TestDataFactory.getOperationHours(testSite.Id);
        opHours3.Name = 'Wednesday';
        opHours3.Open_Time__c = System.now().time();
        opHours3.Closing_Time__c = system.now().addHours(3).time();
        lstOPHours.add(opHours3);
        
        Operation_Hours__c opHours4 = TestDataFactory.getOperationHours(testSite.Id);
        opHours4.Name = 'Thursday';
        opHours4.Open_Time__c = System.now().time();
        opHours4.Closing_Time__c = system.now().addHours(3).time();
        lstOPHours.add(opHours4);
        
        Operation_Hours__c opHours5 = TestDataFactory.getOperationHours(testSite.Id);
        opHours5.Name = 'Friday';
        opHours5.Open_Time__c = System.now().time();
        opHours5.Closing_Time__c = system.now().addHours(3).time();
        lstOPHours.add(opHours5);
        
        Operation_Hours__c opHours6 = TestDataFactory.getOperationHours(testSite.Id);
        opHours6.Name = 'Saturday';
        opHours6.Open_Time__c = System.now().time();
        opHours6.Closing_Time__c = system.now().addHours(3).time();
        lstOPHours.add(opHours6);
        
        Operation_Hours__c opHours7 = TestDataFactory.getOperationHours(testSite.Id);
        opHours7.Name = 'Sunday';
        opHours7.Open_Time__c = System.now().time();
        // opHours7.Closing_Time__c = system.now().addHours(3).time(); // Closing time not set to evaluate the condition for null value for time
        lstOPHours.add(opHours7);
        
        database.insert(lstOPHours);
    }
    
    @isTest
    static void testMethodGetSites(){
        
        test.startTest();
        
        List<GROW_SiteOpHoursCtrl.SiteWrapper> lstWrapper = GROW_SiteOpHoursCtrl.getSites();
        
        test.stopTest();
    }
}