force-app/main/default/objects/B2B_Customer_Delivery_Date__c/B2B_Customer_Delivery_Date__c.object-meta.xml
<CustomObject>
    <description>This object will have the upcoming delivery dates for a B2B Customer. Data in this object will be inserted by a batch process.</description>
    <label>Preferred Delivery Day</label>
    <nameField>
        <displayFormat>CDD-{0000}</displayFormat>
        <label>Delivery Day Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Preferred Delivery Days</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/B2B_Customer_Delivery_Date__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>B2B_Customer_Delivery_Dates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/B2B_Customer_Delivery_Date__c/fields/Day__c.field-meta.xml
<CustomField>
    <fullName>Day__c</fullName>
    <label>Preferred Delivery Day</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Delivery_Dates</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Delivery_Dates.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Monday</fullName>
    </customValue>
    <customValue>
        <fullName>Tuesday</fullName>
    </customValue>
    <customValue>
        <fullName>Wednesday</fullName>
    </customValue>
    <customValue>
        <fullName>Thursday</fullName>
    </customValue>
    <customValue>
        <fullName>Friday</fullName>
    </customValue>
    <masterLabel>Delivery Dates</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DateController.cls
public with sharing class DateController {
    @AuraEnabled(cacheable=true)
    public static List<Map<String, String>> getDeliveryDaysByUser() {
        List<Map<String, String>> responseList = new List<Map<String, String>>();
        Map<String, String> response = new Map<String, String>();
        try {

            Id contactId = [Select contactid from User where id =: Userinfo.getUserid()].contactId;
            Id accountId  = [Select AccountID from Contact where id =: contactId].AccountId;
            List<B2B_Customer_Delivery_Date__c> customerDeliveryDatesList = [
                SELECT Id, Day__c
                FROM B2B_Customer_Delivery_Date__c
                WHERE Customer__c=:accountId
            ];

            String customerDeliveryDays = '';

            for(B2B_Customer_Delivery_Date__c bb :customerDeliveryDatesList) {
                customerDeliveryDays+= bb.Day__c+',';
            }
            response.put('status', 'success');
            response.put('data', customerDeliveryDays);
            responseList.add(response);
        } catch(Exception e) {
            response.put('status','error');
            response.put('message',e.getMessage());
            responseList.add(response);
        }
        return responseList;
    }
}