force-app/main/default/objects/Public_Holiday__c/Public_Holiday__c.object-meta.xml
<CustomObject>
    <label>Public Holiday</label>
    <nameField>
        <label>Public Holiday Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Public Holidays</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Public_Holiday__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Public Holiday Date</description>
    <inlineHelpText>Public Holiday Date</inlineHelpText>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Public_Holiday__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NSW</fullName>
            </value>
            <value>
                <fullName>VIC</fullName>
            </value>
            <value>
                <fullName>SA</fullName>
            </value>
            <value>
                <fullName>WA</fullName>
            </value>
            <value>
                <fullName>NT</fullName>
            </value>
            <value>
                <fullName>QLD</fullName>
            </value>
            <value>
                <fullName>ACT</fullName>
            </value>
            <value>
                <fullName>TAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PublicHolidaysControllerTest.cls
@isTest
public class PublicHolidaysControllerTest {
    @testSetup
    static void setup() { 
        
        List<Account> accountList = new List<Account>();
        Account account1 = new Account();
        account1.Name = 'Test1';
        account1.BillingState = 'NSW';
        accountList.add(account1);
        insert accountList;

        Public_Holiday__c publicHoliday = new Public_Holiday__c();
        publicHoliday.State__c = 'NSW';
        publicHoliday.Date__c = Date.today();
        publicHoliday.Name = 'Public Holiday';
        insert publicHoliday;


    }
    
    
    static testMethod void testCase1() {
        Test.startTest();

        Account account = [
            SELECT Id
            FROM Account
            WHERE Name='Test1'
        ];

        PublicHolidaysController.getAllPublicHolidays(account.Id);

        Test.stopTest();
    }
}