force-app/main/default/objects/Public_Holiday__c/Public_Holiday__c.object-meta.xml
<CustomObject>
    <label>Public Holiday</label>
    <nameField>
        <label>Public Holiday Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Public Holidays</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Public_Holiday__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Public Holiday Date</description>
    <inlineHelpText>Public Holiday Date</inlineHelpText>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Public_Holiday__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NSW</fullName>
            </value>
            <value>
                <fullName>VIC</fullName>
            </value>
            <value>
                <fullName>SA</fullName>
            </value>
            <value>
                <fullName>WA</fullName>
            </value>
            <value>
                <fullName>NT</fullName>
            </value>
            <value>
                <fullName>QLD</fullName>
            </value>
            <value>
                <fullName>ACT</fullName>
            </value>
            <value>
                <fullName>TAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PublicHolidaysController.cls
public class PublicHolidaysController {
    
    @AuraEnabled
    public static List<Map<String, String>> getAllPublicHolidays(String accountId) {
        List<Map<String, String>> responseList = new List<Map<String, String>>();
        Map<String, String> response = new Map<String, String> ();
        try{
            String billingState = [
                SELECT billingState 
                FROM Account 
                WHERE Id=:accountId
            ].billingState;

            List<Public_Holiday__c> publicHolidayList = [
                SELECT Id, Name, Date__c
                FROM Public_Holiday__c
                WHERE State__c=:billingState
            ];

            response.put('status', 'success');
            response.put('data', JSON.serialize(publicHolidayList));
            responseList.add(response);
        }
        catch (Exception e) {
            response.put('status', 'error');
            response.put('message', e.getMessage()+'<br/>'+e.getStackTraceString());
            responseList.add(response);
        }
        return responseList;
    }
}